# Generated by Django 6.0.6 on 2026-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='step',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='seat',
            name='agent',
            field=models.CharField(choices=[('random', 'Random'), ('heuristic', 'Heuristic'), ('llm', 'LLM')], default='random', max_length=16),
        ),
    ]
