# Generated by Django 6.0.6 on 2026-10-07 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.CharField(max_length=64)),
                ('dsl_version', models.CharField(max_length=16)),
                ('program', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('supported', 'Supported'), ('partial', 'Partial'), ('unsupported', 'Unsupported')], max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('reason_kind', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('compiled_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'card_rules',
                'constraints': [models.UniqueConstraint(fields=('oracle_id', 'dsl_version'), name='card_rule_per_dsl_version')],
            },
        ),
    ]
